# Generated by Django 2.1.5 on 2019-03-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0008_auto_20190301_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_datetime', models.DateTimeField(verbose_name='Send time')),
            ],
            options={
                'verbose_name': 'Bot Message',
                'verbose_name_plural': 'Bot Messages',
            },
        ),
        migrations.CreateModel(
            name='MessageAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ImageField(upload_to='messages/audio')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_audios', to='chains.Message')),
            ],
            options={
                'verbose_name': 'Message audio',
                'verbose_name_plural': 'Message audios',
            },
        ),
        migrations.CreateModel(
            name='MessageButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Button title')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Button link')),
                ('deactivate_chain_id', models.PositiveIntegerField(verbose_name='Deactivate chain ID')),
                ('activate_chain_id', models.PositiveIntegerField(verbose_name='Activate chain ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_buttons', to='chains.Message')),
            ],
            options={
                'verbose_name': 'Message button',
                'verbose_name_plural': 'Message buttons',
            },
        ),
        migrations.CreateModel(
            name='MessageDelay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.IntegerField(verbose_name='Delay time (sec)')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_delays', to='chains.Message')),
            ],
            options={
                'verbose_name': 'Message delay',
                'verbose_name_plural': 'Message delays',
            },
        ),
        migrations.CreateModel(
            name='MessageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='messages/files')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_files', to='chains.Message')),
            ],
            options={
                'verbose_name': 'Message file',
                'verbose_name_plural': 'Message files',
            },
        ),
        migrations.CreateModel(
            name='MessageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='messages/images')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_images', to='chains.Message')),
            ],
            options={
                'verbose_name': 'Message text',
                'verbose_name_plural': 'Message texts',
            },
        ),
        migrations.CreateModel(
            name='MessageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_links', to='chains.Message')),
            ],
            options={
                'verbose_name': 'Message link',
                'verbose_name_plural': 'Message links',
            },
        ),
        migrations.CreateModel(
            name='MessagesChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('start_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'Messages Chain',
                'verbose_name_plural': 'Messages Chains',
            },
        ),
        migrations.CreateModel(
            name='MessageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4096)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_texts', to='chains.Message')),
            ],
            options={
                'verbose_name': 'Message text',
                'verbose_name_plural': 'Message texts',
            },
        ),
        migrations.CreateModel(
            name='MessageVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.ImageField(upload_to='messages/videos')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_videos', to='chains.Message')),
            ],
            options={
                'verbose_name': 'Message video',
                'verbose_name_plural': 'Message videos',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains_message', to='chains.MessagesChain'),
        ),
    ]
