# Generated by Django 2.1.5 on 2019-03-11 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageaudio',
            name='audio',
            field=models.FileField(upload_to='messages/audio'),
        ),
        migrations.AlterField(
            model_name='messageaudio',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='chains.Message'),
        ),
        migrations.AlterField(
            model_name='messagebutton',
            name='activate_chain_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Activate chain ID'),
        ),
        migrations.AlterField(
            model_name='messagebutton',
            name='deactivate_chain_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Deactivate chain ID'),
        ),
        migrations.AlterField(
            model_name='messagebutton',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='chains.Message'),
        ),
        migrations.AlterField(
            model_name='messagedelay',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delay', to='chains.Message'),
        ),
        migrations.AlterField(
            model_name='messagefile',
            name='file',
            field=models.FileField(upload_to='messages/files'),
        ),
        migrations.AlterField(
            model_name='messagefile',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chains.Message'),
        ),
        migrations.AlterField(
            model_name='messageimage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chains.Message'),
        ),
        migrations.AlterField(
            model_name='messagelink',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='chains.Message'),
        ),
        migrations.AlterField(
            model_name='messagetext',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='chains.Message'),
        ),
        migrations.AlterField(
            model_name='messagevideo',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='chains.Message'),
        ),
        migrations.AlterField(
            model_name='messagevideo',
            name='video',
            field=models.FileField(upload_to='messages/videos'),
        ),
    ]
