# Generated by Django 2.1.5 on 2019-03-27 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chains', '0004_auto_20190325_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_to',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
