# Generated by Django 2.1.5 on 2019-03-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0006_auto_20190327_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_type',
            field=models.CharField(choices=[('text', 'Text'), ('link', 'Link'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('file', 'File'), ('map', 'Map'), ('timer', 'Timer'), ('button', 'Button')], default='text', max_length=10),
            preserve_default=False,
        ),
    ]
