# Generated by Django 2.1.5 on 2019-01-23 10:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(16)], verbose_name='cardholder number')),
                ('cc_name', models.CharField(max_length=256, verbose_name='cardholder name')),
                ('cc_expiry_date', models.DateField(verbose_name='expiry date')),
                ('cvv_code', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(4)], verbose_name='CVV code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
