# Generated by Django 2.1.5 on 2019-01-23 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_creditcardprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcardprofile',
            options={'verbose_name': 'Credit Card Profile', 'verbose_name_plural': 'Credit Card Profiles'},
        ),
        migrations.AlterField(
            model_name='creditcardprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
