# Generated by Django 2.1.5 on 2019-01-23 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190123_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardprofile',
            name='cc_expiry_date',
            field=models.DateField(verbose_name='expiry date MM/YYYY'),
        ),
        migrations.AlterField(
            model_name='creditcardprofile',
            name='cc_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.RegexValidator('^\\d{1,10}$')], verbose_name='cardholder number'),
        ),
        migrations.AlterField(
            model_name='creditcardprofile',
            name='cvv_code',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(9999)], verbose_name='CVV code'),
        ),
    ]
