# Generated by Django 2.1.5 on 2019-01-29 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190123_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardprofile',
            name='cc_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\d{13,16}$')], verbose_name='cardholder number'),
        ),
    ]
