# Generated by Django 2.1.5 on 2019-02-26 16:10

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_profiles/avatars'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/London'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
