# Generated by Django 2.1.5 on 2019-02-28 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190228_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
