# Generated by Django 2.1.5 on 2019-02-28 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_devicedata_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicedata',
            old_name='activity',
            new_name='last_activity',
        ),
    ]
