# Generated by Django 2.1.5 on 2019-04-03 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bot_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
