# Generated by Django 2.1.5 on 2019-02-04 12:09

from django.db import migrations
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_botmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessages',
            name='position',
            field=positions.fields.PositionField(default=-1),
        ),
    ]
