# Generated by Django 2.1.5 on 2019-02-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_botmessages_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessages',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
