# Generated by Django 2.1.5 on 2019-02-21 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190131_1242'),
        ('bots', '0005_auto_20190205_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViberBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('token', models.CharField(max_length=256)),
                ('active', models.BooleanField(default=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'Viber Bot',
                'verbose_name_plural': 'Viber Bots',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('token', models.CharField(max_length=256)),
                ('active', models.BooleanField(default=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'WhatsApp Bot',
                'verbose_name_plural': 'WhatsApp Bots',
            },
        ),
        migrations.AddField(
            model_name='botmessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='messages/audio'),
        ),
        migrations.AddField(
            model_name='botmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='messages/files'),
        ),
        migrations.AddField(
            model_name='botmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='messages/images'),
        ),
        migrations.AddField(
            model_name='botmessage',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botmessage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='messages/video'),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='chat_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
