# Generated by Django 2.1.5 on 2019-03-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_auto_20190221_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botmessage',
            name='chain',
        ),
        migrations.RemoveField(
            model_name='messageschain',
            name='project',
        ),
        migrations.DeleteModel(
            name='BotMessage',
        ),
        migrations.DeleteModel(
            name='MessagesChain',
        ),
    ]
