# Generated by Django 2.1.5 on 2019-03-25 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bots', '0007_auto_20190311_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('api_key', models.CharField(max_length=256)),
                ('active', models.BooleanField(default=True)),
                ('bot_type', models.CharField(choices=[('telegram', 'Telegram'), ('facebook', 'Facebook'), ('viber', 'Viber'), ('whats_up', "What's up")], max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='facebookbot',
            name='project',
        ),
        migrations.RemoveField(
            model_name='telegrambot',
            name='project',
        ),
        migrations.RemoveField(
            model_name='viberbot',
            name='project',
        ),
        migrations.RemoveField(
            model_name='whatsappbot',
            name='project',
        ),
        migrations.DeleteModel(
            name='FacebookBot',
        ),
        migrations.DeleteModel(
            name='TelegramBot',
        ),
        migrations.DeleteModel(
            name='ViberBot',
        ),
        migrations.DeleteModel(
            name='WhatsAppBot',
        ),
    ]
