# Generated by Django 2.1.5 on 2019-04-03 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bots', '0009_botbase_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='botbase',
            name='leads',
            field=models.ManyToManyField(blank=True, related_name='lead_bots', to=settings.AUTH_USER_MODEL),
        ),
    ]
