# Generated by Django 2.1.5 on 2019-01-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autowebinarfakechatmessage',
            options={'verbose_name': 'Fake autowebinar message', 'verbose_name_plural': 'Fake autowebinar messages'},
        ),
        migrations.AlterModelOptions(
            name='webinarfakechatmessage',
            options={'verbose_name': 'Fake webinar message', 'verbose_name_plural': 'Fake webinar messages '},
        ),
        migrations.AlterField(
            model_name='autowebinarfakechatmessage',
            name='nickname',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Fake nickname'),
        ),
        migrations.AlterField(
            model_name='webinarfakechatmessage',
            name='nickname',
            field=models.CharField(blank=True, max_length=63, null=True, verbose_name='Fake nickname'),
        ),
    ]
