# Generated by Django 2.1.5 on 2019-02-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190131_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='webinarfakechatmessage',
            options={'verbose_name': 'Fake webinar message', 'verbose_name_plural': 'Fake webinar messages'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='cover_time',
        ),
        migrations.AddField(
            model_name='autowebinar',
            name='cover_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cover time before video starts (in seconds)'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='cover_time',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cover time before video starts (in seconds)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
