# Generated by Django 2.1.5 on 2019-02-25 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190225_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webinar',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
    ]
