# Generated by Django 2.1.5 on 2019-02-26 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_webinar_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='slug',
            field=models.SlugField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='viewers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
