# Generated by Django 2.1.5 on 2019-03-11 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_auto_20190301_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebinarOnlineWatchersCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fake', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0, null=True)),
                ('viewers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('webinar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Webinar')),
            ],
        ),
    ]
