# Generated by Django 2.1.5 on 2019-03-11 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_webinaronlinewatcherscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinaronlinewatcherscount',
            name='viewers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
