# Generated by Django 2.1.5 on 2019-03-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20190311_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinaronlinewatcherscount',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
