# Generated by Django 2.1.5 on 2019-03-14 16:22

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20190311_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webinaronlinewatcherscount',
            old_name='count',
            new_name='fake_count',
        ),
        migrations.RemoveField(
            model_name='webinar',
            name='active_chats',
        ),
        migrations.AddField(
            model_name='webinar',
            name='chat_type',
            field=models.CharField(blank=True, choices=[('private', 'private'), ('public', 'public')], default='public', max_length=14),
        ),
        migrations.AddField(
            model_name='webinaronlinewatcherscount',
            name='fake_count_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True),
        ),
    ]
