# Generated by Django 2.1.5 on 2019-04-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20190314_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinar',
            name='cover_time',
        ),
    ]
