version: "3"
services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass12pass
      POSTGRES_USER: webinar_user
      POSTGRES_DB: webinar_dev
    ports:
      - '5432:5432'
    tty: true
    stdin_open: true
  redis:
    image: redis
    ports:
      - '6379:6379'
  celery:
    build: .
    volumes:
      - '.:/app'
    command: celery worker -A Project_W --loglevel=INFO
    env_file:
      - vars.env
  django:
    build: .
    volumes:
      - '.:/app'
    ports:
      - '8000:8000'
    tty: true
    stdin_open: true
    command: python3 manage.py runserver 0.0.0.0:8000 --settings=Project_W.settings.dev
    env_file:
      - vars.env
networks:
  default:
    external:
      name: nginx-rtmp_default